/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.DeleteDB;
import database.GetDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import object.Answer;
import object.Questions;
import object.Subject;
import object.Topic;

/**
 *
 * @author DuongSon
 */
public class FindAndDeleteQuestion extends javax.swing.JFrame {
    
    DefaultTableModel tableModel;
    private ArrayList<Subject> listSubjects = new GetDB().getListSubject();  
    private int subjectID, topicID, level=1;

    /**
     * Creates new form FindAndDeleteQuestion
     */
    public FindAndDeleteQuestion() {
        initComponents();
        setBounds(50,50,800,500);
        setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addCbSuject();      // them mon hoc   
    }
    private void addTable(ArrayList<Questions> list){       
        tableModel = (DefaultTableModel)tbList.getModel();
        tableModel.setColumnIdentifiers(new Object[]{  // ten bang
            "Mã câu hỏi", "Nội dung","Độ khó"
        });
        tableModel.setRowCount(0);
        for(Questions s : list){
            tableModel.addRow(new Object[]{
                s.getQuestionID(),s.getQuestionContent(),s.getQuestionLevel()
            });
        }
    }
    private void addCbSuject(){       // add mon hoc vao combobox
        cbSubject.removeAll();
        for(Subject s : listSubjects){            
            cbSubject.addItem(s.getSubjectName());
        }
        
    }
    private void addCbTopic(int id){    // add chu de vao combobox // truyen tham so id là ma mon hoc 
        cbTopic.removeAllItems();
        ArrayList<Topic> listTopics = new GetDB().getListTopic(id);
        for(Topic s : listTopics){            
            cbTopic.addItem(s.getTopicName());
        }              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbSubject = new javax.swing.JComboBox<>();
        cbTopic = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbList = new javax.swing.JTable();
        lbID = new javax.swing.JLabel();
        lbAn1 = new javax.swing.JLabel();
        lbAn3 = new javax.swing.JLabel();
        lbAn2 = new javax.swing.JLabel();
        lbAn4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lble1 = new javax.swing.JLabel();
        lble2 = new javax.swing.JLabel();
        lble3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tìm kiến & Xóa Câu hỏi ");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm ");

        cbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubjectActionPerformed(evt);
            }
        });

        cbTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTopicActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Môn học :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Chủ đề: ");

        tbList.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tbList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã câu hỏi", "Nội dung ", "Mức độ "
            }
        ));
        tbList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbList);

        lbID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbID.setText("Mã câu hỏi :");

        lbAn1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbAn1.setText("Đáp án 1: ");

        lbAn3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbAn3.setText("Đáp án 2:");

        lbAn2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbAn2.setText("Đáp án 3: ");

        lbAn4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbAn4.setText("Đáp án 4:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Xóa ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        lble1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lble1.setText("jLabel4");

        lble2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lble2.setText("jLabel4");

        lble3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lble3.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAn3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbAn1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbAn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbAn4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lble1))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lble2)
                                .addGap(148, 148, 148)
                                .addComponent(lble3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lble1)
                    .addComponent(lble2)
                    .addComponent(lble3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAn2)
                    .addComponent(lbAn1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void printNumberOfLevel(ArrayList<Questions> list){
        int le1 = 0, le2 = 0, le3 = 0;
        for(Questions s : list){
            if (s.getQuestionLevel()==1) le1++;
            else if (s.getQuestionLevel()==2) le2++;
            else le3++;           
        }
        lble1.setText("Câu dễ: "+le1);
        lble2.setText("Câu trung bình : "+le2);
        lble3.setText("Câu khó : "+le3);
        
    }
    private void cbTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTopicActionPerformed
        Object selected = cbTopic.getSelectedItem();
            if (selected != null) // kiem tra neu co chu de thi moi lay ve duoc
            {            
                String topicname = selected.toString();
                ArrayList<Topic> listTopics = new GetDB().getListTopic(subjectID);
                int id=0;
                for(Topic s : listTopics){
                    if (s.getTopicName().equals(topicname))
                    id = s.getTopicID();
                }
                topicID  =id;
                ArrayList<Questions> listQuestions  =new GetDB().getListQuestionFromTopic(id);
                addTable(listQuestions);
                printNumberOfLevel(listQuestions);
            }        
    }//GEN-LAST:event_cbTopicActionPerformed

    private void cbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubjectActionPerformed
        Object selected = cbSubject.getSelectedItem();
        String subjectname = selected.toString();

        int id=0;
        for(Subject s : listSubjects){
            if (s.getSubjectName().equals(subjectname))
            id = s.getSubjectID();
        }
        subjectID  = id;  // lay duoc id cua mon hoc -> hien thi ra cac chu  de tuong ung 
        addCbTopic(id); // sau khi them  chon mon hoc thi moi chon duoc chu de 
    }//GEN-LAST:event_cbSubjectActionPerformed

    private void tbListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMouseClicked
        int index = tbList.getSelectedRow();
        TableModel model = tbList.getModel();
        int id = Integer.parseInt(model.getValueAt(index, 0).toString());        
        ArrayList<Questions> listQuestionses = new GetDB().getListQuestionFromID(id);
        Questions que = listQuestionses.get(0);
        ArrayList<Answer> listAnswers = new GetDB().getListAnswerFromQuestion(id);      
        
        lbID.setText("Mã số: "+id);
        jTextArea1.setText("Nội dung : " + que.getQuestionContent());
        jTextArea1.setWrapStyleWord(true);
        lbAn1.setText("Đáp án 1: "+listAnswers.get(0).getAnswerContent());
        lbAn2.setText("Đáp án 2: "+listAnswers.get(1).getAnswerContent());
        lbAn3.setText("Đáp án 3: "+listAnswers.get(2).getAnswerContent());
        lbAn4.setText("Đáp án 4: "+listAnswers.get(3).getAnswerContent());
    }//GEN-LAST:event_tbListMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new QuestionManagerment().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] options = {"Xóa  ", "Thôi không xóa "};
                    int n = JOptionPane.showOptionDialog(rootPane,
                                    "Chắc chắn muốn xóa ? ",
                                    "Question",
                                    JOptionPane.YES_NO_OPTION,
                                    JOptionPane.QUESTION_MESSAGE,
                                    null,
                                    options,
                                    options[0]);
        if (n == JOptionPane.YES_OPTION) {
            //
            int index = tbList.getSelectedRow();
            TableModel model = tbList.getModel();
            int id = Integer.parseInt(model.getValueAt(index, 0).toString());  
            try {
                new DeleteDB().deleteQuestion(id);
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công !");  
                addCbSuject(); 
                lbID.setText("Mã số: "+id);
                jTextArea1.setText("Nội dung : " );
                jTextArea1.setWrapStyleWord(true);
                lbAn1.setText("Đáp án 1: ");
                lbAn2.setText("Đáp án 2: ");
                lbAn3.setText("Đáp án 3: ");
                lbAn4.setText("Đáp án 4: ");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Xóa không thành công !");
            }
            //
        } else if (n == JOptionPane.NO_OPTION) {                        
            return;
        } else {                       
        }        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindAndDeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindAndDeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindAndDeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindAndDeleteQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindAndDeleteQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbSubject;
    private javax.swing.JComboBox<String> cbTopic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbAn1;
    private javax.swing.JLabel lbAn2;
    private javax.swing.JLabel lbAn3;
    private javax.swing.JLabel lbAn4;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lble1;
    private javax.swing.JLabel lble2;
    private javax.swing.JLabel lble3;
    private javax.swing.JTable tbList;
    // End of variables declaration//GEN-END:variables
}
